[env]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5AtomS3
  m5stack/M5Unified
  fastled/FastLED
  bblanchon/ArduinoJson

[env:usb]
upload_protocol = esptool

[env:ota]
upload_protocol = espota
upload_port = soil-moisture-atom-s3.local
