[env:m5stack-atoms3]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5AtomS3
  m5stack/M5Unified
  fastled/FastLED
  bblanchon/ArduinoJson
