[env:usb]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  m5stack/M5Unified
  bblanchon/ArduinoJson

[env:ota]
extends = env:usb
upload_protocol = espota
upload_port = weight-m5stickc-plus2.local
upload_flags = --timeout=300
