[env]
platform = espressif32
board = unit-cams3-5mp
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<main.cpp>
  -<hardware-check.cpp>

[env:usb]
upload_protocol = esptool

[env:ota]
upload_protocol = espota
upload_port = plantory-camera.local

[env:hardware-check]
upload_protocol = esptool
build_src_filter =
  +<hardware-check.cpp>
  -<main.cpp>
